site_name: MF-SINDy Docs
site_url: https://filippozacchei.github.io/2025_visiting/
repo_url: https://github.com/filippozacchei/2025_visiting
exclude_docs: |
  notebooks/forecastingDoublePendulum.ipynb
  notebooks/forecastingMF.ipynb

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tabs
    - content.code.copy
  palette:
    - scheme: default
      primary: blue
      accent: pink

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.arithmatex:
      generic: true

plugins:
  - search
  - mkdocs-jupyter:
      execute: true
      allow_errors: false
      include_source: true

nav:
  - Overview: index.md
  - Examples:
      - Overview: examples.md
      - Lorenz Part 1: notebooks/lorenz/part1.ipynb
      - Lorenz Part 2: notebooks/lorenz/part2.ipynb
      - Hopf Part 1: notebooks/hopf/part1.ipynb
      - Hopf Part 2: notebooks/hopf/part2.ipynb
  - API Reference: api.md
  - Methodology: methodology.md

extra_css: []
extra_javascript:
  - javascripts/mathjax.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
